config/routes.rb
Wallchalking::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :property_types
  resources :listings
  resources :facilities
  resources :reviews

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "authentications", registrations: "registrations"}
  resources :users

  resources :listings do
    collection do
      post 'like'
      post 'unlike'
      post 'save'
      post 'unsave'
    end  
  end

  
  match 'search' => 'search#search_result'
  
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  
  attr_accessible :address, :bathrooms, :beds, :city, :country, :description, :size, :title, :zipcode, :facility_ids
  attr_accessible :monthly_rent, :deposit_amount, :property_type_id, :available_from, :image, :published, :property_for
  
  # Association
  has_and_belongs_to_many :facilities
  belongs_to :property_type
  belongs_to :user
  has_one :saved_listing

  validates_presence_of :title, :address, :zipcode, :city, :size, :property_for
   
  mount_uploader :image, ListingImageUploader
  is_impressionable
  acts_as_votable

  #Scopes
  scope :by_city, ->(city_name) {where(:city => city_name)}
  scope :published, -> {where(:published => true)}
  
  
  def add_to_saved_listings(user_id)
    SavedListing.create(:user_id => user_id, :listing_id => self.id)
  end
  
  def remove_from_saved_listings(user_id)
    SavedListing.delete_all(:user_id => user_id, :listing_id => self.id)
  end

  
  def saved?(user_id)
    SavedListing.where(:user_id => user_id, :listing_id => self.id).any?
  end

  
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_filter :authorize_list_owner, :only => [:edit]
  
  impressionist :actions=>[:show]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @listings }
    end
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @listing = Listing.find(params[:id])
    @review = Review.new
    @reviews = Review.where(:listing_id => params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @listing }
    end
  end

  # GET /listings/new
  # GET /listings/new.json
  def new
    @listing = Listing.new
    @facilities = Facility.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @listing }
    end
  end

  # GET /listings/1/edit
  def edit
    @listing = Listing.find(params[:id])
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(params[:listing])
    @listing.user_id = current_user.id
    @listing.country = "Austria"
#    @listing.listing_image.name = "test.jpg"
    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render json: @listing, status: :created, location: @listing }
      else
        format.html { render action: "new" }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /listings/1
  # PUT /listings/1.json
  def update
    @listing = Listing.find(params[:id])

    respond_to do |format|
      if @listing.update_attributes(params[:listing])
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy

    respond_to do |format|
      format.html { redirect_to listings_url }
      format.json { head :no_content }
    end
  end

  def authorize_list_owner
    @listing = Listing.find(params[:id])
    unless current_user == @listing.user
      redirect_to listings_path, :notice => 'Operation not allowed.'
    end
  end
  
  def like    
    @listing = Listing.find(params[:id])
    @listing.liked_by current_user
    respond_to do |format|
      format.js
    end      
  end
  
  def unlike    
    @listing = Listing.find(params[:id])
    @listing.unliked_by current_user
    respond_to do |format|
      format.js
    end      
  end
  
  def save
    @listing = Listing.find(params[:id])
    @listing.add_to_saved_listings(current_user.id)
    
    respond_to do |format|
      format.js
    end
  end
  
  def unsave
    @listing = Listing.find(params[:id])
    @listing.remove_from_saved_listings(current_user.id)
    
    respond_to do |format|
      format.js
    end
  end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.haml
= simple_form_for @listing do |f|
  - if @listing.errors.any?
    #error_explanation
      %h2= "#{pluralize(@listing.errors.count, "error")} prohibited this listing from being saved:"
      %ul
        - @listing.errors.full_messages.each do |msg|
          %li= msg

  <!-- div class="ui-widget">
  <label for="tags">Tags: </label>
  <input id="tags">
  </div -->
  = f.input :title
  = f.input :address
  = f.input :zipcode
  %div{:class => "ui-widget"}
    = f.input :city
  = f.input :country, priority: [ "Austria" ], input_html: {disabled: "disabled"}
  = f.input :description
  = f.input :beds
  = f.input :bathrooms
  = f.input :size  
  = f.association :property_type, :label => "Property Type"
  = f.input :property_for, as: :select, collection: ["Sale", "Rent"], prompt: "Select property for"
  %span.hidden_field
    = f.input :monthly_rent
  = f.input :deposit_amount
  = f.association :facilities, :as => :check_boxes
  %label
    Available From
  = f.input_field :available_from, as: :string, :class => 'datepicker'
  .hint
    Format: "yyyy/mm/dd"
  =# file_field(:listing, :listing_images)
  = f.input :image, multiple: true
  

  .actions
    = f.submit 'Review and Publish'

app/views/listings/_like_and_save.html.haml
.loader
- if user_signed_in?
  %p
    .save-link
      - if @listing.saved?(current_user.id)    
        = link_to "Unsave", unsave_listings_path(:id => @listing.id), :remote => true, :method => :post, :class => 'unsave'
      - else
        = link_to "Save", save_listings_path(:id => @listing.id), :remote => true, :method => :post, :class => 'save'
  %p
    .like-link
      - if current_user.voted_for? @listing    
        = link_to "Unlike", unlike_listings_path(:id => @listing.id), :remote => true, :method => :post, :class => 'unlike'
      - else    
        = link_to "Like", like_listings_path(:id => @listing.id), :remote => true, :method => :post, :class => 'like'

app/views/listings/edit.html.haml
%h1 Editing listing

= render 'form'

= link_to 'Show', @listing
\|
= link_to 'Back', listings_path

app/views/listings/index.html.haml
%h1 Listing listings

%table
  %tr
    %th Title
    %th Address
    %th Zipcode
    %th City
    %th Country
    %th Description
    %th Beds
    %th Bathrooms
    %th Size
    %th Facility
    %th Property Type
    %th
    %th
    %th

  - @listings.each do |listing|
    %tr
      %td= listing.title
      %td= listing.address
      %td= listing.zipcode
      %td= listing.city
      %td= listing.country
      %td= listing.description
      %td= listing.beds
      %td= listing.bathrooms
      %td= listing.size
      %td
        - listing.facilities.each do |facility|
          = facility.name
      %td= listing.property_type.name
      %td= link_to 'Show', listing
      %td= link_to 'Edit', edit_listing_path(listing)
      %td= link_to 'Destroy', listing, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Listing', new_listing_path

app/views/listings/like.js.erb
$(".loader").hide('slow');
$(".like-link a").removeClass('like').addClass('unlike').text('Unlike').attr("href", "<%= unlike_listings_path(:id => @listing.id) %>");

app/views/listings/new.html.haml
%h1 New listing
#map-canvas.pull-right Map Canvas
= render 'form'

= link_to 'Back', listings_path



:javascript  
  $(document).ready(function(){
    $("#listing_address").focusout(function(){
      add = $("#listing_address").val();
      codeAddress($("#listing_address").val());
    });
    /*
    $("#listing_zipcode").focusout(function(){
      add = $("#listing_address").val()+", "+$("#listing_zipcode").val()
      codeAddress(add);
    });
    
    $("#listing_city").focusout(function(){
      add = $("#listing_address").val()+", "+$("#listing_zipcode").val()+", "+$("#listing_city").val()
      codeAddress(add);
    });*/
    
  });
  var geocoder;
  var map;
  function initialize() {
  geocoder = new google.maps.Geocoder();
  var latlng = new google.maps.LatLng(48.2081743, 16.37381890000006);
  var mapOptions = {
    zoom: 12,
    center: latlng
  }
  map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
  }

  function codeAddress(city) {
    initialize();
    var address = city;
    alert(city);
    geocoder.geocode( { 'address': address}, function(results, status) {
      if (status == google.maps.GeocoderStatus.OK) {
        map.setCenter(results[0].geometry.location);
        var marker = new google.maps.Marker({
            map: map,
            position: results[0].geometry.location
        });
      } else {
        console.log('Geocode was not successful for the following reason: ' + status);
      }
    });
  }

  google.maps.event.addDomListener(window, 'load', initialize);

app/views/listings/save.js.erb
$(".loader").hide('slow');
$(".save-link a").removeClass('save').addClass('unsave').text('Unsave').attr("href", "<%= unsave_listings_path(:id => @listing.id) %>");

app/views/listings/show.html.haml
%p#notice= notice
.contact-landlord.pull-right
  = simple_form_for :contact_landlord, :url => "/contact-landlord" do |f|
    = f.input :name, :label => false, :placeholder => "Name"
    = f.input :email, :label => false, :placeholder => "Email"
    = f.input :phone, :label => false, :placeholder => "Phone Number"
    = f.input :message, :label => false, :as => :text, :placeholder => "Type your message here..."
    = f.submit "Contact"
    / By sending, you agree to WallChalking's Terms of use and Privacy Policy
%p
  %b Page Views
  = @listing.impressionist_count

= render :partial => 'like_and_save' 

%p
  %b Title:
  = @listing.title
%p
  %b Address:
  = @listing.address
%p
  %b Zipcode:
  = @listing.zipcode
%p
  %b City:
  = @listing.city
%p
  %b Country:
  = @listing.country
%p
  %b Description:
  = @listing.description
%p
  %b Beds:
  = @listing.beds
%p
  %b Bathrooms:
  = @listing.bathrooms
%p
  %b Size:
  = @listing.size
%p
  %b Facility:
  - @listing.facilities.each do |facility|
    = facility.name

%p
  %b Image:
  = image_tag @listing.image
- if current_user == @listing.user
  - unless @listing.published?
    = simple_form_for @listing do |f|
      = f.input :published, :as => :hidden, :input_html => {:checked => true, :value => 1 }
      = f.submit 'Publish', :class => 'btn btn-primary'

  = link_to 'Edit', edit_listing_path(@listing), :class => 'btn btn-primary'
  - if @listing.published
    = link_to 'Back', listings_path, :class => 'btn btn-primary'

    
= render :partial => "reviews/form", :locals => {:listing_id => @listing.id}
/
  - @reviews.each do |review|
    = render :partial => "reviews/review_item", :locals => {:review => review}

app/views/listings/unlike.js.erb
$(".loader").hide('slow');
$(".like-link a").removeClass('unlike').addClass('like').text('Like').attr("href", "<%= like_listings_path(:id => @listing.id) %>");

app/views/listings/unsave.js.erb
$(".loader").hide('slow');
$(".save-link a").removeClass('unsave').addClass('save').text('Save').attr("href", "<%= save_listings_path(:id => @listing.id) %>");