config/routes.rb
Wallchalking::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :property_types
  resources :listings
  resources :facilities
  resources :reviews

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "authentications", registrations: "registrations"}
  resources :users

  resources :listings do
    collection do
      post 'like'
      post 'unlike'
      post 'save'
      post 'unsave'
    end  
  end

  
  match 'search' => 'search#search_result'
  
end

app/controllers/property_types_controller.rb
class PropertyTypesController < ApplicationController
  # GET /property_types
  # GET /property_types.json
  def index
    @property_types = PropertyType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @property_types }
    end
  end

  # GET /property_types/1
  # GET /property_types/1.json
  def show
    @property_type = PropertyType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @property_type }
    end
  end

  # GET /property_types/new
  # GET /property_types/new.json
  def new
    @property_type = PropertyType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @property_type }
    end
  end

  # GET /property_types/1/edit
  def edit
    @property_type = PropertyType.find(params[:id])
  end

  # POST /property_types
  # POST /property_types.json
  def create
    @property_type = PropertyType.new(params[:property_type])

    respond_to do |format|
      if @property_type.save
        format.html { redirect_to @property_type, notice: 'Property type was successfully created.' }
        format.json { render json: @property_type, status: :created, location: @property_type }
      else
        format.html { render action: "new" }
        format.json { render json: @property_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /property_types/1
  # PUT /property_types/1.json
  def update
    @property_type = PropertyType.find(params[:id])

    respond_to do |format|
      if @property_type.update_attributes(params[:property_type])
        format.html { redirect_to @property_type, notice: 'Property type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @property_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /property_types/1
  # DELETE /property_types/1.json
  def destroy
    @property_type = PropertyType.find(params[:id])
    @property_type.destroy

    respond_to do |format|
      format.html { redirect_to property_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/property_types_helper.rb
module PropertyTypesHelper
end

app/views/property_types/_form.html.haml
= form_for @property_type do |f|
  - if @property_type.errors.any?
    #error_explanation
      %h2= "#{pluralize(@property_type.errors.count, "error")} prohibited this property_type from being saved:"
      %ul
        - @property_type.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/property_types/edit.html.haml
%h1 Editing property_type

= render 'form'

= link_to 'Show', @property_type
\|
= link_to 'Back', property_types_path

app/views/property_types/index.html.haml
%h1 Listing property_types

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @property_types.each do |property_type|
    %tr
      %td= property_type.name
      %td= link_to 'Show', property_type
      %td= link_to 'Edit', edit_property_type_path(property_type)
      %td= link_to 'Destroy', property_type, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Property type', new_property_type_path

app/views/property_types/new.html.haml
%h1 New property_type

= render 'form'

= link_to 'Back', property_types_path

app/views/property_types/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @property_type.name

= link_to 'Edit', edit_property_type_path(@property_type)
\|
= link_to 'Back', property_types_path