config/routes.rb
Wallchalking::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :property_types
  resources :listings
  resources :facilities
  resources :reviews

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "authentications", registrations: "registrations"}
  resources :users

  resources :listings do
    collection do
      post 'like'
      post 'unlike'
      post 'save'
      post 'unsave'
    end  
  end

  
  match 'search' => 'search#search_result'
  
end

app/models/facility.rb
class Facility < ActiveRecord::Base
  attr_accessible :name
  
  validates_presence_of :name
  
  has_and_belongs_to_many :listings
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  before_filter :authenticate_admin
  
  # GET /facilities
  # GET /facilities.json
  def index
    @facilities = Facility.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @facilities }
    end
  end

  # GET /facilities/1
  # GET /facilities/1.json
  def show
    @facility = Facility.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @facility }
    end
  end

  # GET /facilities/new
  # GET /facilities/new.json
  def new
    @facility = Facility.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @facility }
    end
  end

  # GET /facilities/1/edit
  def edit
    @facility = Facility.find(params[:id])
  end

  # POST /facilities
  # POST /facilities.json
  def create
    @facility = Facility.new(params[:facility])

    respond_to do |format|
      if @facility.save
        format.html { redirect_to @facility, notice: 'Facility was successfully created.' }
        format.json { render json: @facility, status: :created, location: @facility }
      else
        format.html { render action: "new" }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /facilities/1
  # PUT /facilities/1.json
  def update
    @facility = Facility.find(params[:id])

    respond_to do |format|
      if @facility.update_attributes(params[:facility])
        format.html { redirect_to @facility, notice: 'Facility was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facilities/1
  # DELETE /facilities/1.json
  def destroy
    @facility = Facility.find(params[:id])
    @facility.destroy

    respond_to do |format|
      format.html { redirect_to facilities_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/views/facilities/_form.html.haml
= form_for @facility do |f|
  - if @facility.errors.any?
    #error_explanation
      %h2= "#{pluralize(@facility.errors.count, "error")} prohibited this facility from being saved:"
      %ul
        - @facility.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/facilities/edit.html.haml
%h1 Editing facility

= render 'form'

= link_to 'Show', @facility
\|
= link_to 'Back', facilities_path

app/views/facilities/index.html.haml
%h1 Listing facilities

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @facilities.each do |facility|
    %tr
      %td= facility.name
      %td= link_to 'Show', facility
      %td= link_to 'Edit', edit_facility_path(facility)
      %td= link_to 'Destroy', facility, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Facility', new_facility_path

app/views/facilities/new.html.haml
%h1 New facility

= render 'form'

= link_to 'Back', facilities_path

app/views/facilities/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @facility.name

= link_to 'Edit', edit_facility_path(@facility)
\|
= link_to 'Back', facilities_path